config/routes.rb
Rails.application.routes.draw do

	root 'lists#index'

	# LISTS
  get    'lists/:id',          to: 'lists#show',      as: 'list'
  patch  'lists/:id',          to: 'lists#update'
	delete 'lists/:id',          to: 'lists#destroy'
  get    'lists',              to: 'lists#index',     as: 'lists'
	post   'lists',              to: 'lists#create'
  get    'lists/:id/edit',     to: 'lists#edit',      as: 'edit_list'
	# ENTRIES via LIST
	get    'lists/:id/new',      to: 'lists#new_entry', as: 'new_entry'
	post   'lists/:id/create',   to: 'entries#create',  as: 'create_entry'
	# ENTRIES
  get    'entry/:id',          to: 'entries#edit',    as: 'edit_entry'
  post   'entry/:id',          to: 'entries#create',  as: 'entries'
  patch  'entry/:id',          to: 'entries#update',  as: 'entry'
  delete 'entry/:id',          to: 'entries#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :list
	validates :name, presence: true
	after_create :custom_validation

	# name description quantity metric

	private

		def custom_validation
			self.quantity = 1.0  if (self.quantity.blank?)
			self.save
		end

end

app/models/list.rb
class List < ApplicationRecord
	has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
		@entries = Entry.all
  end

	def new
	end

	def create
		list = List.find params[:id]
		@entry = list.entries.new params_accept(:entry)
		if (@entry.save)
			flash[:success] = "New entry added."
			redirect_to list_path list
		else
			render "new"
		end
	end

  def edit
		@entry = Entry.find params[:id]
		@method = "patch"
  end

	def update
		@entry = Entry.find params[:id]
		if (@entry.update_attributes! params_accept(:entry))
			flash[:success] = "Updated entry."
			redirect_to list_path @entry.list
		else
			flash[:danger] = "Couldn't update entry."
			redirect_to edit_entry_path @entry
		end
	end

	def destroy
		entry = Entry.find params[:id]
		if (entry.destroy!)
			flash[:success] = "Entry has been deleted."
			redirect_to list_path entry.list
		else
			flash[:danger] = "Entry couldn't be deleted."
			redirect_to entry_path entry
		end
	end

	private

		def params_accept target
			case (target)
			when :entry
				return params.require(:entry).permit(:name, :description, :quantity)
			end
		end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
		@lists = List.all
  end

  def show
		@list = List.find params[:id]
		@entries = @list.entries
  end

	def create
		list = List.create! params_accept(:list)
		redirect_to list_path list
	end

	def new_entry
		# New Entry in List
		list = List.find params[:id]
		@entry = Entry.new list_id: list.id
		@method = "post"
		render 'entries/new'
	end

	def update
		list = List.find params[:id]
		if (list.update_attributes! params_accept(:list))
			flash[:success] = "Updated List."
		else
			flash[:danger] = "There was a problem updating this List."
		end
		redirect_to list_path list
	end

  def destroy
		list = List.find params[:id]
		if (list.destroy!)
			flash[:success] = "List has been deleted."
			redirect_to root_path
		else
			flash[:danger] = "There was a problem deleting the List."
			redirect_to list_path list
		end
  end

	private

		def params_accept target
			case target
			when :list
				params.require(:list).permit(:name)
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (base)
		base.blank? ? "Roselist" : "#{base} | Roselist"
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry, method: @method do |form| %>
	<%= render 'shared/error_messages', object: form.object %>

	<div class="row">
		<div class="col-xs-8">
			<%= form.text_field :name, class: "entry entry__title form-control", value: @entry.name, placeholder: "Name" %>
		</div>
		<div class="col-xs-4 pull-right">
			<%= form.text_field :quantity, class: "entry entry__quantity form-control", value: @entry.quantity, placeholder: "Stk" %>
		</div>
		<div class="col-xs-8">
			<%= form.text_area :description, class: "entry entry__description form-control", value: @entry.description, placeholder: "Description" %>
		</div>
	</div>

	<%= form.submit "SUBMIT BUTTON", id: "entry-form-submit", class: "hidden" %>
<% end %>

app/views/entries/_save_button.html.erb
<label type="submit" for="entry-form-submit" class="btn btn-primary col-xs-6 navigation--button">
	<%= (@method == "post" ? "Create" : (@method == "patch" ? "Save" : "BUTTON")) %>
</label>

app/views/entries/edit.html.erb
<% provide :title, "New Entry - #{@entry.list.name}" %>
<% provide :button, "entries/save_button" %>

<div class="row">
	<div class="col-xs-6">
		<%= link_to "Back", list_path(@entry.list), class: "btn btn-default entry__btn-back" %>
	</div>
	<div class="col-xs-6">
		<%= link_to "Delete", entry_path(@entry), method: "delete", data: {confirm: "Delete entry?"}, class: "btn btn-danger pull-right" %>
	</div>
</div>

<%= render 'form' %>

app/views/entries/new.html.erb
<% provide :title, "New Entry - #{@entry.list.name}" %>
<% provide :button, "entries/save_button" %>

<%= link_to "Back", list_path(@entry.list), class: "btn btn-default entry__btn-back" %>

<%= render 'entries/form' %>

app/views/layouts/_navigation_bottom.html.erb
<nav class="navigation--nav navbar navbar-default navbar-fixed-bottom">
	<div class="container-fluid">
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="row">
			<div class="btn-group col-xs-12">
				<div class="row">
					<%= link_to "Home", root_path, class: "btn btn-default col-xs-6 navigation--button" %>
					<% unless (yield(:button).blank?) %>
						<%= render yield(:button) %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/_navigation_top.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container-fluid">
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="row nav navbar-nav">
			<li class="col-xs-12 text-center"><%= link_to "Home", root_path %></li>
		</ul>
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<title><%= full_title yield(:title) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%#= render 'layouts/navigation_top' %>
		<%= render 'layouts/header' %>
    <div class="view-wrapper container">
			<% flash.each do |type,msg| %>
				<div class="alert alert-<%= type %>"><%= msg %></div>
			<% end %>
    	<%= yield %>
    </div>
  </body>
	<%= render 'layouts/navigation_bottom' %>
</html>

app/views/lists/_new_entry_button.html.erb
<a href="<%= new_entry_path %>" class="btn btn-default col-xs-6 navigation--button" id="new_entry_button">
	New Entry
</a>
<label for="update_list_button" class="btn btn-primary col-xs-6 hidden navigation--button" id="update_list_label">
	Update List
</label>

app/views/lists/_new_list_button.html.erb
<div class="new_list_dialog hidden">
	<%= form_for List.new, method: "post", url: { action: "create" } do |f| %>
		<div class="form-group">
			<%= f.label :name, "Name", class: "control-label" %>
			<%= f.text_field :name, class: "form-control input--transparent", autofocus: true %>
			<%= f.submit "Create List", class: "btn btn-primary new_list_dialog__button" %>
		</div>
	<% end %>
</div>

<button type="button" id="new_list_button" class="btn btn-default col-xs-6 navigation--button">
	New List
</button>

<%= javascript_include_tag "_new_list_button" %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/index.html.erb
<%= provide :title, "" %>
<%= provide :button, "lists/new_list_button" %>

<h1>All Lists</h1>

<ul class="list-group">
	<% @lists.each do |list| %>
			<a href="<%= list_path list %>" class="button--anchor">
			<li class="list-group-item li--hover">
				<div class="row">
					<span class="col-sm-6">
						<%= list.name %>
					</span>
					<span class="col-sm-6 pull-right text-right">
						<%= list.created_at.strftime "%d. %B '%y" %>
					</span>
				</div>
			</li>
		</a>
	<% end %>
</ul>

app/views/lists/new.html.erb
<% provide :title, "New Entry" %>
<% provide :button, "entries/save_button" %>
<%= render 'layouts/entry_form' %>

app/views/lists/show.html.erb
<%= provide :title, @list.name %>
<%= provide :button, "lists/new_entry_button" %>

<div class="row title--row">
	<%= form_for @list, method: "patch" do |f| %>
		<h3>
			<%= f.text_field :name, value: @list.name, class: "col-xs-8 input--transparent", id: "list_title" %>
			<%= f.submit "Rename", class: "hidden", id: "update_list_button" %>
		</h3>
	<% end %>
	<div class="col-xs-4">
		<%= link_to "Delete", list_path(@list), method: "delete", class: "btn btn-danger pull-right", data: { confirm: "List will be deleted forever. Delete?" } %>
	</div>
</div>

<ul class="list-group">
	<% @entries.each do |entry| %>
			<a href="<%= edit_entry_path entry %>" class="button--anchor">
			<li class="list-group-item li--hover">
				<div class="row">
					<span class="col-sm-6">
						<%= entry.name %>
					</span>
					<span class="col-sm-6 pull-right text-right">
						<%#= entry.created_at.strftime "%d. %B '%y" %>
						<%= entry.quantity %>
					</span>
				</div>
			</li>
		</a>
	<% end %>
</ul>

<%= javascript_include_tag "_list_rename" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>